### ISSUE TITLE
den fetch throws

### ISSUE THREAD

**Issue by zoechi** [seaneagan/den#37]
```
 (master) $ den fetch
Unhandled exception:
Uncaught Error: The null object does not have a method 'forEach'.

NoSuchMethodError: method not found: 'forEach'
Receiver: null
Arguments: [Closure: (dynamic, dynamic) => dynamic]
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      Pubspec.versionConstraints.addGroup (package:den_api/src/pubspec.dart:119)
#3      Pubspec.versionConstraints (package:den_api/src/pubspec.dart:130)
#4      fetchOrPull.<anonymous closure> (package:den/src/util.dart:15)
#5      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

pubspec.yaml

``` yaml
environment:
  sdk: '>=1.9.0 <2.0.0'

description: Dart client for the Docker remote API

dependencies:
  collection: '^1.1.0'
  crypto: '^0.9.0'
  http: '^0.11.2'
  stack_trace: '>= 1.2.1 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 < 0.13.0'
  grinder: '^0.7.0'

dependency_overrides:
```
