### ISSUE TITLE
Weird result of `den spec` 

### ISSUE THREAD

**Issue by zoechi** [seaneagan/den#39]
Somehow I'm not able make `den spec` produce a proper `pubspec.yaml`.

``` yaml
name: bwu_dart_archive_downloader
authorGuenter Zoechbauer <guenter@gzoechbauer.com>: # name <email>
homepagehttps://github.com/bwu-dart/bwu_dart_archive_downloader: # https://github.com/user/repo
version: 0.1.0
environment:
  sdk: '>=1.0.0 <2.0.0'
description: Typed API for the site where Dart artifacts like SDK, Dartium, ContentShell, ChromeDriver and API docs can be downloaded.
```
